### ISSUE TITLE
md.reqUserLogin cause an error

### ISSUE THREAD

**Issue by QuantBull** [shixiongfei/napi-ctp#1]
code as below:
```js
md.on('front-connected', (...args) => {
  console.log('FrontConnected', ...args);
  md.reqUserLogin({
    BrokerID: "****",
    UserID: "****",
    Password: "****",
  });
});
```

console output:
```bash
$ node test.js 
v6.6.7_20220613 14:52:04.1708
v6.6.7_20220613 14:52:04.1708
Connect to 180.166.103.21:55205
Session 1759117313 Connected
FrontConnected undefined
Segmentation fault
```
Thanks your good job on the ctp node wrapper!
Can you help to take a look at the issue? I am not sure why occurs the `Segmentation fault`, but what is certain is that it is caused by `md.reqUserLogin`.

**Comment by shixiongfei** [comment]
It seems to be a problem with my handwritten type declaration. I have submitted a new version, you can try it out.

**Comment by QuantBull** [comment]
Thanks for your reply. But it still doesn't work and the same error occurred.
I searched the issue by keyword "Segmentation fault", and found a link: [Segmentation fault细谈](https://zhuanlan.zhihu.com/p/42545141). I hope it can be helpful.

**Comment by shixiongfei** [comment]
Thank you, this project isn't really finished yet, I'll take a look sometime.

**Comment by shixiongfei** [comment]
@southwhale Maybe fixed, you can try it again.

**Comment by QuantBull** [comment]
Sure. It works very well currently. Many thanks. @shixiongfei
