### ISSUE TITLE
It seems ReqOrderInsert will not trigger `rsp-order-insert` and `err-rtn-order-insert` events

### ISSUE THREAD

**Issue by QuantBull** [shixiongfei/napi-ctp#4]
1. I tried the `ReqOrderInsert` API, and whether it succeeded or failed, it would not trigger the `rsp-order-insert`, which is not expected.
2. When the failure occurred (such as `CTP: 平今仓位不足`), the `err-rtn-order-insert` was not triggered, but the `rsp-error` was triggered, which seems not expected.
3. When succeed, the `rtn-order` event was triggered, which is expected.

I'm not sure if 1 and 2 perform the same as the CTP C++ API.

**Comment by shixiongfei** [comment]
The behavior of napi-ctp and CTP C++ API is consistent, and how messages respond depends on the CTP server, the napi-ctp is simply forwarded to JavaScript.
